language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - ILLUMINATE_VERSION=4.1.*
  - ILLUMINATE_VERSION=4.2.*
  - ILLUMINATE_VERSION=5.0.*
  - ILLUMINATE_VERSION=5.1.*
  - ILLUMINATE_VERSION=5.2.*
  - ILLUMINATE_VERSION=5.3.*
  - ILLUMINATE_VERSION=5.4.*
  - ILLUMINATE_VERSION=5.5.*
  - ILLUMINATE_VERSION=5.6.*
  - ILLUMINATE_VERSION=5.7.*
  - ILLUMINATE_VERSION=5.8.*
  - ILLUMINATE_VERSION=6.*
  - ILLUMINATE_VERSION=7.*

jobs:
  include:
    - dist: trusty
      php: 5.5
      env: ILLUMINATE_VERSION=4.1.*
    - dist: trusty
      php: 5.5
      env: ILLUMINATE_VERSION=4.2.*
    - dist: trusty
      php: 5.5
      env: ILLUMINATE_VERSION=5.0.*
    - dist: trusty
      php: 5.5
      env: ILLUMINATE_VERSION=5.1.*
    - dist: trusty
      php: 5.5
      env: ILLUMINATE_VERSION=5.2.*
  exclude:
    - php: 5.6
      env: ILLUMINATE_VERSION=5.5.*
    - php: 5.6
      env: ILLUMINATE_VERSION=5.6.*
    - php: 5.6
      env: ILLUMINATE_VERSION=5.7.*
    - php: 5.6
      env: ILLUMINATE_VERSION=5.8.*
    - php: 5.6
      env: ILLUMINATE_VERSION=6.*
    - php: 5.6
      env: ILLUMINATE_VERSION=7.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.0
      env: ILLUMINATE_VERSION=6.*
    - php: 7.0
      env: ILLUMINATE_VERSION=7.*
    - php: 7.1
      env: ILLUMINATE_VERSION=6.*
    - php: 7.1
      env: ILLUMINATE_VERSION=7.*

before_install:
  - composer self-update
  - if [ "$ILLUMINATE_VERSION" != "" ]; then composer require "illuminate/database:${ILLUMINATE_VERSION}" --no-update; fi;

install: travis_wait composer update --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpunit --coverage-clover ./clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml
